const mutationTypes = {
  CHANGE_PROJECT: 'CHANGE_PROJECT',
  UPDATE_INTERACTION: 'UPDATE_INTERACTION',
  RESET_INTERACTION: 'RESET_INTERACTION',
  RESET_PREVIOUS: 'RESET_PREVIOUS'
};

module.exports = mutationTypes;
