const mutationTypes = {
  CHANGE_PROJECT: 'CHANGE_PROJECT',
  UPDATE_INTERACTION: 'UPDATE_INTERACTION',
  UPDATE_FROMCASE: 'UPDATE_FROMCASE',
  UPDATE_ASSETS: 'UPDATE_ASSETS',
  RESET_INTERACTION: 'RESET_INTERACTION',
  RESET_PREVIOUS: 'RESET_PREVIOUS',
  RESET_FROMCASE: 'RESET_FROMCASE'
};

module.exports = mutationTypes;
